### ISSUE TITLE
Scientific Computing with Ryzen

### ISSUE THREAD

**Issue by jshousephd** [andrie/version.compare#10]
Do you have any insight or tests that compare MRO  on Windows OR Linux on an Intel Chip vs. an AMD Ryzen Chip (preferably 1600 or 1700 or 1800 or the 2xxx, esp. threadrippers) series.  Specifically for the matrix operations for which MKL excels.  I am considering a threadripper (gen 1 or gen2) and I have been unable to properly find the answer to this question.

**Comment by jshousephd** [comment]
I was able to find [this link ](http://www.sisoftware.eu/2017/08/11/amd-threadripper-review-benchmarks-cpu-16-core-performance/) suggesting that Threadripper is still falling well short of where it should be for scientific computing.

**Comment by andrie** [comment]
Interesting question, but not really an issue on `version.compare`.  You may have more luck posting this question at a discussion forum like https://community.rstudio.com/.
